In [1]:
import pandas as pd
import pymysql
from tqdm import tqdm
import os
import pickle
import numpy as np
def connect_db():
    return pymysql.connect(
        host="127.0.0.1",
        user='root',
        password='240812',
        database='lol_data',
        port=3307
    )

# DB 연결 함수

# 챔피언 ID, 태그 사전 파일 저장 함수

In [68]:
def get_champion_dict(conn):
    champion_dict_query = "SELECT champion_id, champion_name, tags FROM champion_dict"
    
    champion_dict = pd.read_sql_query(champion_dict_query, conn)

    with open("table_data/champion_dict.pkl", "wb") as f:
        pickle.dump(champion_dict, f)
    return champion_dict
conn = connect_db()
get_champion_dict(conn)
conn.close()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_2912\89247483.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  champion_dict = pd.read_sql_query(champion_dict_query, conn)

# 챔피언 참여자ID 라인타입 사전 파일 저장 함수

In [18]:
def get_champion_participant_id(conn):
    champion_participant_id_query = "SELECT match_id, participant_id, champion_id, position FROM champion_participant_id"
    champion_participant_id = pd.read_sql_query(champion_participant_id_query, conn)
    with open("table_data/champion_participant_id.pkl", "wb") as f:
        pickle.dump(champion_participant_id, f)
    return champion_participant_id
conn = connect_db()
get_champion_participant_id(conn)
conn.close()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_6472\3442806052.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  champion_participant_id = pd.read_sql_query(champion_participant_id_query, conn)

# 게임 종료 파일 저장 함수

In [6]:
def get_game_end(conn):
    game_end_query = "SELECT match_id, real_timestamp, timestamp, winning_team FROM game_end"
    game_end = pd.read_sql_query(game_end_query, conn)
    with open("table_data/game_end.pkl", "wb") as f:
        pickle.dump(game_end, f)
    return game_end
conn = connect_db()
get_game_end(conn)
conn.close()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_6472\226839149.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  game_end = pd.read_sql_query(game_end_query, conn)

# 타워 파괴 파일 저장 함수

In [ ]:
def get_building_kill(conn):
    building_kill_query = "SELECT match_id, assist_id, building_type, participant_id, line_type, team_id, timestamp, tower_type FROM building_kill"
    building_kill = pd.read_sql_query(building_kill_query, conn)
    with open("table_data/building_kill.pkl", "wb") as f:
        pickle.dump(building_kill, f)
    return building_kill
conn = connect_db()
get_building_kill(conn)
conn.close()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_10216\2079252993.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  building_kill = pd.read_sql_query(building_kill_query, conn)

# 챔피언 20분 이후 솔킬 파일 저장함수

In [41]:
def get_champion_kill(conn):
    champion_kill_query = "SELECT match_id, participant_id, timestamp FROM champion_kill where assist_id IS NULL AND timestamp > 1200000"
    champion_kill = pd.read_sql_query(champion_kill_query, conn)
    with open("table_data/champion_solo_kill_after20.pkl", "wb") as f:
        pickle.dump(champion_kill, f)
    return champion_kill
conn = connect_db()
get_champion_kill(conn)
conn.close()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_10216\1483398865.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  champion_kill = pd.read_sql_query(champion_kill_query, conn)

# 6.태그별 평균 수치 데이터 파일 저장함수

In [71]:
def tag_avg_stat():
    with open("dashboard_data/champion_stats.pkl", "rb") as f:
        champion_dataframes = pickle.load(f)

    with open("table_data/champion_dict.pkl", "rb") as f:
        champion_df = pickle.load(f)
    tag_mapping = {
        "Assassin": "암살자",
        "Fighter": "전사",
        "Mage": "마법사",
        "Marksman": "원거리 공격",
        "Support": "지원가",
        "Tank": "탱커"
    }

    tag_avg_dataframes = {}
    for tag in set(tag for tags in champion_df['tags'] for tag in eval(tags)):

        champions_with_tag = champion_df[champion_df['tags'].apply(lambda x: tag in eval(x))]['champion_name'].tolist()
        
        tag_data = pd.concat([champion_dataframes[champion] for champion in champions_with_tag if champion in champion_dataframes])
        
        tag_avg_df = tag_data.groupby("분").mean().reset_index()


        mapped_tag = tag_mapping.get(tag, tag)  
        tag_avg_dataframes[mapped_tag] = tag_avg_df
    with open("dashboard_data/tag_avg_stats.pkl", "wb") as f:
        pickle.dump(tag_avg_dataframes, f)
tag_avg_stat()

In [72]:
with open("dashboard_data/tag_avg_stats.pkl", "rb") as f:
    data = pickle.load(f)
data['암살자']

,분,챔피언에게 가한 피해량,챔피언에게 가한 마법 피해량,챔피언에게 가한 물리 피해량,받은 피해량,총 획득한 골드량,총 경험치량,평균 누적 와드 설치 횟수,평균 누적 와드 제거 횟수
0,0,0.000000,0.000000,0.000000,0.000000,500.020455,0.000000,1.001384,1.001105
1,1,37.186364,8.143182,27.813636,40.288636,509.113636,0.381818,1.012561,1.022886
2,2,206.393182,41.063636,157.834091,452.256818,613.452273,216.084091,1.057348,1.091973
3,3,513.884091,119.375000,367.595455,1109.411364,979.209091,741.240909,1.328070,1.064068
4,4,884.111364,217.863636,610.302273,1699.286364,1352.329545,1171.572727,2.003420,1.122814
5,5,1268.072727,324.240909,861.072727,2301.404545,1725.447727,1617.768182,2.285352,1.150950
6,6,1652.159091,433.979545,1110.052273,2941.115909,2094.306818,2068.059091,2.660780,1.200677
7,7,2096.213636,565.215909,1393.902273,3673.561364,2463.679545,2492.713636,3.346120,1.306948
8,8,2563.979545,703.752273,1691.302273,4428.811364,2865.702273,2974.040909,3.716641,1.438280
9,9,3069.384091,855.781818,2006.813636,5219.784091,3272.034091,3453.263636,4.208959,1.579148
10,10,3623.593182,1020.556818,2350.068182,6044.643182,3669.052273,3917.281818,4.906655,1.754132
11,11,4259.925000,1216.759091,2738.252273,6940.168182,4109.422727,4424.470455,5.384116,1.948223
12,12,4943.786364,1430.697727,3154.579545,7899.979545,4554.927273,4901.213636,5.957934,2.137525
13,13,5633.786364,1645.529545,3577.440909,8854.911364,4987.186364,5365.245455,6.678416,2.350475
14,14,6345.145455,1865.052273,4012.981818,9840.734091,5463.479545,5889.784091,7.254943,2.559066
15,15,8126.047727,2412.765909,5110.461364,12447.831818,6787.552273,7321.329545,7.906700,2.815268
16,16,8168.818182,2443.779545,5107.131818,12385.181818,6670.595455,7233.177273,8.644430,3.042161
17,17,8754.811364,2642.272727,5440.506818,13095.313636,6965.806818,7576.720455,9.244848,3.327405
18,18,9942.786364,3019.229545,6151.704545,14626.263636,7666.715909,8349.361364,9.894084,3.573868
19,19,10997.504545,3364.525000,6774.656818,15960.215909,8226.250000,8976.893182,10.568686,3.879343
20,20,11881.079545,3662.638636,7282.445455,17020.395455,8646.972727,9461.163636,11.170298,4.171300
21,21,12987.447727,4036.509091,7912.513636,18407.565909,9187.177273,10100.993182,11.866895,4.431343
22,22,14278.361364,4449.509091,8668.786364,20086.852273,9834.540909,10872.884091,12.600302,4.771441
23,23,15732.950000,4948.936364,9494.220455,21885.979545,10520.513636,11677.434091,13.302148,5.131552
24,24,17097.452273,5410.261364,10273.647727,23532.886364,11116.929545,12377.027273,14.160909,5.386927
25,25,18516.852273,5894.168182,11082.061364,25286.431818,11733.697727,13089.497727,14.880555,5.712764
26,26,19970.779545,6409.875000,11885.070455,26992.325000,12335.104545,13804.170455,15.638457,6.030786
27,27,21543.502273,6925.884091,12796.125000,28922.988636,13044.577273,14646.038636,16.245005,6.325802
28,28,23188.675000,7468.479545,13732.384091,30799.097727,13745.445455,15480.638636,17.141091,6.635400
29,29,24947.009091,8065.490909,14733.279545,32946.702273,14509.211364,16388.086364,17.875316,7.086650
30,30,26716.311364,8683.000000,15723.618182,35153.695455,15264.129545,17315.025000,18.810452,7.318050
31,31,28680.040909,9270.597727,16902.654545,37364.493182,16019.513636,18220.786364,19.320884,7.623930
32,32,30031.220455,9776.109091,17610.036364,39104.593182,16491.843182,18852.795455,20.468327,7.877864
33,33,32307.813636,10536.461364,18867.693182,41840.145455,17493.602273,20066.502273,20.724014,8.283323
34,34,33767.359091,11046.554545,19704.734091,43661.525000,17945.184091,20675.554545,21.708825,8.403836
35,35,35431.106818,11568.288636,20657.354545,45517.886364,18508.202273,21380.852273,22.957686,8.920325
36,36,37438.836364,12394.015909,21616.313636,47693.043182,19190.175000,22220.704545,23.753057,8.851859
37,37,39135.725000,12926.922727,22623.065909,50115.020455,19839.145455,23047.652273,24.923767,9.165307
38,38,40639.811364,13293.802273,23549.861364,51989.065909,20401.672727,23780.372727,26.937422,10.016137
39,39,43374.022727,14163.263636,25065.304545,55134.022727,21293.343182,24896.315909,27.194243,9.825735
40,40,45153.377273,14821.954545,25998.870455,56864.863636,21859.138636,25541.143182,28.934079,9.924257
41,41,48735.722727,16243.115909,28017.218182,61512.788636,23495.895455,27581.006818,31.975194,10.831734
42,42,48506.820455,15580.563636,28289.475000,63357.236364,23678.750000,27789.084091,33.503439,11.716987
43,43,49572.976190,17216.069048,27214.869048,62888.185714,23286.845238,27809.392857,35.665027,10.817138
44,44,52193.447619,18107.900000,28967.830952,65139.504762,23942.809524,28305.290476,42.266646,11.628092
45,45,56684.990244,18196.865854,32476.202439,71522.102439,26281.170732,31095.209756,44.480059,11.959845
46,46,58497.848718,16872.535897,35076.910256,73882.146154,26768.938462,31841.323077,41.802780,11.382613
47,47,56610.438235,14742.252941,35013.123529,71764.876471,24883.529412,29423.052941,46.297438,13.000000
48,48,61570.996667,20812.360000,34920.386667,81966.630000,26897.196667,32783.586667,51.484845,9.200000
49,49,56323.130769,18605.169231,31601.046154,70645.734615,25922.757692,31345.415385,57.291663,20.857143
50,50,58968.437500,19870.862500,31819.958333,77556.150000,26468.266667,32359.312500,51.500000,12.333333
51,51,69751.935000,25220.025000,36689.790000,85551.910000,30129.325000,37373.150000,102.416650,13.750000
52,52,78099.954545,17762.545455,49485.181818,93538.772727,31627.181818,38675.318182,68.000000,NaN
53,53,116468.857143,44061.142857,63811.714286,128579.857143,42610.000000,50737.428571,NaN,NaN

# 5.이벤트 파일 합치는 함수

In [59]:
def load_and_merge_champion_data():
    # 챔피언 데이터 로드
    with open("table_data/champion_main_stats.pkl", "rb") as f:
        champion_main_stats = pickle.load(f)
    
    with open("table_data/champion_ward_placement_stats.pkl", "rb") as f:
        champion_ward_placement_stats = pickle.load(f)
    
    with open("table_data/champion_ward_removal_stats.pkl", "rb") as f:
        champion_ward_removal_stats = pickle.load(f)
    
    merged_data = {}

    for champion_name in champion_main_stats.keys():
        main_stats = champion_main_stats.get(champion_name)
        placement_stats = champion_ward_placement_stats.get(champion_name)
        removal_stats = champion_ward_removal_stats.get(champion_name)
        
        # 분 기준으로 병합
        merged_df = pd.merge(main_stats, placement_stats, on='분', how='outer')
        merged_df = pd.merge(merged_df, removal_stats, on='분', how='outer')
        
        # 분 기준으로 정렬
        merged_df = merged_df.sort_values('분').reset_index(drop=True)
        
        # 병합된 데이터프레임을 딕셔너리에 저장
        merged_data[champion_name] = merged_df
    
    with open("dashboard_data/champion_stats.pkl", "wb") as f:
        pickle.dump(merged_data, f)

In [60]:
load_and_merge_champion_data()

In [61]:
with open("dashboard_data/champion_stats.pkl", "rb") as f:
    data = pickle.load(f)
data['카타리나']

,분,챔피언에게 가한 피해량,챔피언에게 가한 마법 피해량,챔피언에게 가한 물리 피해량,받은 피해량,총 획득한 골드량,총 경험치량,평균 누적 와드 설치 횟수,평균 누적 와드 제거 횟수
0,0,0.0,0.0,0.0,0.0,500.0,0.0,1.0000,1.0000
1,1,15.1,10.5,4.2,23.1,504.5,0.2,1.0000,1.0000
2,2,118.4,79.3,36.1,202.3,585.6,191.8,1.0095,NaN
3,3,433.0,273.5,128.2,689.9,896.2,821.9,1.0473,1.1667
4,4,857.1,550.6,233.0,1227.7,1250.2,1337.7,1.8186,1.0244
5,5,1282.8,843.4,326.4,1793.8,1636.6,1869.8,2.0039,1.0135
6,6,1723.0,1165.4,405.6,2353.3,2027.2,2409.2,2.1989,1.0769
7,7,2218.1,1552.3,473.8,2914.5,2410.1,2866.6,2.9676,1.1644
8,8,2744.1,1964.8,545.8,3510.1,2841.2,3412.1,3.1664,1.1570
9,9,3264.1,2378.7,611.0,4103.2,3265.4,3939.6,3.4518,1.3017
10,10,3813.7,2815.0,683.4,4725.0,3662.8,4423.1,4.1026,1.4727
11,11,4533.4,3385.8,778.5,5509.3,4149.3,4999.1,4.2742,1.6080
12,12,5315.2,4016.8,875.1,6315.8,4635.3,5511.4,4.5755,1.8392
13,13,6107.0,4661.5,971.2,7085.1,5090.7,5975.5,5.1557,1.9480
14,14,6882.2,5296.0,1063.4,7876.3,5587.8,6510.4,5.3031,2.1839
15,15,9054.2,7030.8,1355.7,10113.2,7033.0,8096.4,5.5286,2.3080
16,16,8998.0,7033.1,1309.6,10037.2,6891.2,7936.3,5.9886,2.4793
17,17,9667.1,7622.3,1350.7,10683.5,7169.5,8224.3,6.3443,2.5042
18,18,11040.1,8756.5,1509.2,12013.0,7871.3,8973.6,6.6861,2.7024
19,19,12225.0,9762.2,1623.1,13130.8,8448.7,9583.4,6.9341,2.9722
20,20,13124.7,10520.7,1724.4,13951.2,8861.5,10019.7,6.8853,3.3612
21,21,14407.0,11645.9,1813.7,15100.0,9412.8,10625.5,7.0571,3.1868
22,22,16098.3,13076.9,1952.1,16673.0,10186.4,11509.6,7.8343,3.4802
23,23,17854.0,14582.1,2109.9,18228.2,10917.9,12330.7,7.4684,3.6864
24,24,19310.1,15854.7,2193.4,19707.5,11525.0,12984.0,8.4528,4.1477
25,25,21098.6,17396.5,2355.1,20886.3,12175.6,13592.5,8.9060,4.3871
26,26,22794.5,18919.9,2433.4,22513.7,12852.4,14414.6,8.5158,4.0180
27,27,24744.1,20445.2,2726.6,24265.7,13727.5,15336.5,9.9213,4.4747
28,28,26745.6,22229.3,2833.7,25970.0,14517.4,16185.3,10.3939,4.6190
29,29,28494.3,23881.2,2827.5,27664.7,15270.6,17094.7,9.4615,4.8986
30,30,30244.6,25184.6,3167.7,28840.8,15945.2,17918.9,10.7174,5.1053
31,31,32091.0,26814.8,3247.5,30617.9,16533.8,18588.7,10.5600,5.7188
32,32,34182.3,28627.2,3394.4,32511.3,17437.7,19612.0,12.4286,6.0357
33,33,36850.4,31015.8,3510.7,35086.6,18552.5,20789.3,12.9412,5.3043
34,34,38642.6,32040.0,4174.7,36959.6,19218.6,21636.8,10.0833,5.2667
35,35,39149.7,32181.8,4403.8,38074.7,19453.7,22194.3,14.2500,5.8182
36,36,44455.2,36001.4,5613.2,41652.8,21087.3,23919.8,13.0000,4.2500
37,37,42935.2,35519.7,4607.5,40097.8,20385.4,23274.3,11.0000,6.5000
38,38,45497.0,38220.4,4321.1,42116.0,20722.4,23767.1,10.5000,7.3333
39,39,48599.1,41243.5,4244.6,45983.8,23108.8,26423.5,16.0000,4.0000
40,40,53370.6,44058.6,6222.1,46852.4,23096.3,26003.1,14.0000,8.0000
41,41,52939.8,42390.6,7042.6,49848.2,23733.2,28229.8,NaN,7.6000
42,42,48097.9,39969.8,4865.4,46597.8,23553.7,27122.1,11.3333,NaN
43,43,54790.4,42105.6,9134.4,54041.1,24199.5,27726.2,NaN,NaN
44,44,62333.0,52565.0,5840.0,63733.7,26353.9,31589.1,NaN,NaN
45,45,42855.3,28160.0,12078.0,52223.7,19078.3,22938.3,NaN,NaN
46,46,66899.3,50127.0,12706.0,69567.7,28006.3,32821.7,NaN,10.0000
47,47,38361.0,17705.0,17972.5,58931.5,18016.5,22580.0,NaN,NaN
48,48,85048.0,39198.0,40079.0,121053.0,37877.5,48044.0,NaN,NaN

# 대쉬보드

## 1. 챔피언 기본 정보 저장 함수

In [17]:
# 챔피언 기본 스탯 추출 쿼리
def get_champion_main_stats(conn):
    main_stats_query = """
        SELECT 
            cp.champion_id,
            FLOOR(cs.timestamp / 60000) AS minute,
            ROUND(SUM(cs.tdd_to_champion) / COUNT(DISTINCT cs.match_id), 1) AS avg_tdd_to_champion,
            ROUND(SUM(cs.mdd_to_champion) / COUNT(DISTINCT cs.match_id), 1) AS avg_mdd_to_champion,
            ROUND(SUM(cs.pdd_to_champion) / COUNT(DISTINCT cs.match_id), 1) AS avg_pdd_to_champion,
            ROUND(SUM(cs.total_damage_taken) / COUNT(DISTINCT cs.match_id), 1) AS avg_damage_taken,
            ROUND(SUM(cs.total_gold) / COUNT(DISTINCT cs.match_id), 1) AS avg_gold,
            ROUND(SUM(cs.xp) / COUNT(DISTINCT cs.match_id), 1) AS avg_xp
        FROM 
            champion_stat_per_timestamp cs
        JOIN 
            champion_participant_id cp ON cs.match_id = cp.match_id AND cs.participant_id = cp.participant_id
        GROUP BY 
            cp.champion_id, FLOOR(cs.timestamp / 60000)
        ORDER BY 
            cp.champion_id, minute;
    """
    return pd.read_sql_query(main_stats_query, conn)

In [32]:
def save_main_stats_to_pkl():

    conn = connect_db()
    with open("table_data/champion_dict.pkl", "rb") as f:
        champion_dict = pickle.load(f) 

    main_stats = get_champion_main_stats(conn)
    conn.close()

    column_mapping = {
        "minute": "분",
        "avg_tdd_to_champion": "챔피언에게 가한 피해량",
        "avg_mdd_to_champion": "챔피언에게 가한 마법 피해량",
        "avg_pdd_to_champion": "챔피언에게 가한 물리 피해량",
        "avg_damage_taken": "받은 피해량",
        "avg_gold": "총 획득한 골드량",
        "avg_xp": "총 경험치량",
    }

    champion_dataframes = {}

    for champion_id, champion_name in tqdm(champion_dict.items(), desc="Processing Champions"):
        champion_df = main_stats[main_stats['champion_id'] == champion_id].drop(columns=['champion_id'])
        champion_df = champion_df.rename(columns=column_mapping)
        champion_dataframes[champion_name] = champion_df
    with open("table_data/champion_main_stats.pkl", "wb") as f:
        pickle.dump(champion_dataframes, f)

In [33]:
save_main_stats_to_pkl()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_2912\3419427336.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(main_stats_query, conn)
Processing Champions: 100%|██████████| 168/168 [00:00<00:00, 915.49it/s]

In [34]:
with open("table_data/champion_main_stats.pkl", "rb") as f:
    champion_main_stats_data = pickle.load(f)
champion_main_stats_data['카타리나']

,분,챔피언에게 가한 피해량,챔피언에게 가한 마법 피해량,챔피언에게 가한 물리 피해량,받은 피해량,총 획득한 골드량,총 경험치량
2479,0,0.0,0.0,0.0,0.0,500.0,0.0
2480,1,15.1,10.5,4.2,23.1,504.5,0.2
2481,2,118.4,79.3,36.1,202.3,585.6,191.8
2482,3,433.0,273.5,128.2,689.9,896.2,821.9
2483,4,857.1,550.6,233.0,1227.7,1250.2,1337.7
2484,5,1282.8,843.4,326.4,1793.8,1636.6,1869.8
2485,6,1723.0,1165.4,405.6,2353.3,2027.2,2409.2
2486,7,2218.1,1552.3,473.8,2914.5,2410.1,2866.6
2487,8,2744.1,1964.8,545.8,3510.1,2841.2,3412.1
2488,9,3264.1,2378.7,611.0,4103.2,3265.4,3939.6
2489,10,3813.7,2815.0,683.4,4725.0,3662.8,4423.1
2490,11,4533.4,3385.8,778.5,5509.3,4149.3,4999.1
2491,12,5315.2,4016.8,875.1,6315.8,4635.3,5511.4
2492,13,6107.0,4661.5,971.2,7085.1,5090.7,5975.5
2493,14,6882.2,5296.0,1063.4,7876.3,5587.8,6510.4
2494,15,9054.2,7030.8,1355.7,10113.2,7033.0,8096.4
2495,16,8998.0,7033.1,1309.6,10037.2,6891.2,7936.3
2496,17,9667.1,7622.3,1350.7,10683.5,7169.5,8224.3
2497,18,11040.1,8756.5,1509.2,12013.0,7871.3,8973.6
2498,19,12225.0,9762.2,1623.1,13130.8,8448.7,9583.4
2499,20,13124.7,10520.7,1724.4,13951.2,8861.5,10019.7
2500,21,14407.0,11645.9,1813.7,15100.0,9412.8,10625.5
2501,22,16098.3,13076.9,1952.1,16673.0,10186.4,11509.6
2502,23,17854.0,14582.1,2109.9,18228.2,10917.9,12330.7
2503,24,19310.1,15854.7,2193.4,19707.5,11525.0,12984.0
2504,25,21098.6,17396.5,2355.1,20886.3,12175.6,13592.5
2505,26,22794.5,18919.9,2433.4,22513.7,12852.4,14414.6
2506,27,24744.1,20445.2,2726.6,24265.7,13727.5,15336.5
2507,28,26745.6,22229.3,2833.7,25970.0,14517.4,16185.3
2508,29,28494.3,23881.2,2827.5,27664.7,15270.6,17094.7
2509,30,30244.6,25184.6,3167.7,28840.8,15945.2,17918.9
2510,31,32091.0,26814.8,3247.5,30617.9,16533.8,18588.7
2511,32,34182.3,28627.2,3394.4,32511.3,17437.7,19612.0
2512,33,36850.4,31015.8,3510.7,35086.6,18552.5,20789.3
2513,34,38642.6,32040.0,4174.7,36959.6,19218.6,21636.8
2514,35,39149.7,32181.8,4403.8,38074.7,19453.7,22194.3
2515,36,44455.2,36001.4,5613.2,41652.8,21087.3,23919.8
2516,37,42935.2,35519.7,4607.5,40097.8,20385.4,23274.3
2517,38,45497.0,38220.4,4321.1,42116.0,20722.4,23767.1
2518,39,48599.1,41243.5,4244.6,45983.8,23108.8,26423.5
2519,40,53370.6,44058.6,6222.1,46852.4,23096.3,26003.1
2520,41,52939.8,42390.6,7042.6,49848.2,23733.2,28229.8
2521,42,48097.9,39969.8,4865.4,46597.8,23553.7,27122.1
2522,43,54790.4,42105.6,9134.4,54041.1,24199.5,27726.2
2523,44,62333.0,52565.0,5840.0,63733.7,26353.9,31589.1
2524,45,42855.3,28160.0,12078.0,52223.7,19078.3,22938.3
2525,46,66899.3,50127.0,12706.0,69567.7,28006.3,32821.7
2526,47,38361.0,17705.0,17972.5,58931.5,18016.5,22580.0
2527,48,85048.0,39198.0,40079.0,121053.0,37877.5,48044.0

## 2. 와드

In [39]:
# 와드 제거 횟수 데이터 추출
def get_ward_removal_stats(conn):
    ward_removal_query = """
    WITH filtered_ward_kills AS (
        SELECT 
            wk.match_id,
            cp.champion_id,
            FLOOR(wk.timestamp / 60000) AS minute,
            COUNT(*) AS ward_removals
        FROM 
            ward_kill wk
        JOIN 
            champion_participant_id cp ON wk.match_id = cp.match_id AND wk.participant_id = cp.participant_id
        WHERE 
            wk.ward_type != 'UNDEFINED'
        GROUP BY 
            wk.match_id, cp.champion_id, minute
    ),
    cumulative_ward_removals AS (
        SELECT 
            match_id,
            champion_id,
            minute,
            SUM(ward_removals) OVER (PARTITION BY match_id, champion_id ORDER BY minute ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_removals
        FROM 
            filtered_ward_kills
    )
    SELECT 
        champion_id,
        minute,
        AVG(cumulative_removals) AS avg_cumulative_ward_removals
    FROM 
        cumulative_ward_removals
    GROUP BY 
        champion_id, minute
    ORDER BY 
        champion_id, minute;
    """
    return pd.read_sql_query(ward_removal_query, conn)

# 와드 설치 횟수 데이터 추출
def get_ward_placement_stats(conn):
    ward_placement_query = """
    WITH filtered_ward_placements AS (
        SELECT 
            wp.match_id,
            cp.champion_id,
            FLOOR(wp.timestamp / 60000) AS minute,
            COUNT(*) AS ward_placements
        FROM 
            ward_placed wp
        JOIN 
            champion_participant_id cp ON wp.match_id = cp.match_id AND wp.participant_id = cp.participant_id
        GROUP BY 
            wp.match_id, cp.champion_id, minute
    ),
    cumulative_ward_placements AS (
        SELECT 
            match_id,
            champion_id,
            minute,
            SUM(ward_placements) OVER (PARTITION BY match_id, champion_id ORDER BY minute ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_placements
        FROM 
            filtered_ward_placements
    )
    SELECT 
        champion_id,
        minute,
        AVG(cumulative_placements) AS avg_cumulative_ward_placements
    FROM 
        cumulative_ward_placements
    GROUP BY 
        champion_id, minute
    ORDER BY 
        champion_id, minute;
    """
    return pd.read_sql_query(ward_placement_query, conn)

def save_ward_removal_stats_to_pkl():
    conn = connect_db()
    ward_removal_stats = get_ward_removal_stats(conn)
    ward_placement_stats = get_ward_placement_stats(conn)
    conn.close()  
    with open("table_data/ward_removal_stats.pkl", "wb") as f:
        pickle.dump(ward_removal_stats, f)
    with open("table_data/ward_placement_stats.pkl", "wb") as f:
        pickle.dump(ward_placement_stats, f)

In [40]:
save_ward_removal_stats_to_pkl()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_2912\2253587392.py:39: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(ward_removal_query, conn)
C:\Users\dgjja\AppData\Local\Temp\ipykernel_2912\2253587392.py:77: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(ward_placement_query, conn)

### 3. 챔피언별 와드제거 데이터 저장

In [51]:
def save_champion_ward_removal_stats_to_pkl():
    conn = connect_db()
    champion_dict = get_champion_dict(conn)
    conn.close()  
    with open("table_data/ward_removal_stats.pkl", "rb") as f:
        ward_removal_stats = pickle.load(f)
    column_mapping = {
        "minute": "분",
        "avg_cumulative_ward_removals": "평균 누적 와드 제거 횟수",
    }
    champion_dataframes = {}
    for champion_id, champion_name in tqdm(champion_dict.items(), desc="Processing Champions"):
        removal_df = ward_removal_stats[ward_removal_stats['champion_id'] == champion_id][['minute', 'avg_cumulative_ward_removals']]
        removal_df = removal_df.rename(columns=column_mapping)
        champion_dataframes[champion_name] = removal_df
    with open("table_data/champion_ward_removal_stats.pkl", "wb") as f:
        pickle.dump(champion_dataframes, f)

In [52]:
save_champion_ward_removal_stats_to_pkl()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_2912\2181235943.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  champion_dict = pd.read_sql_query(champion_dict_query, conn)
Processing Champions: 100%|██████████| 168/168 [00:00<00:00, 971.05it/s]

In [48]:
with open("dashboard_data/champion_ward_removal_stats.pkl", "rb") as f:
    ward_removal_stats = pickle.load(f)
ward_removal_stats['카타리나'].isnull().sum()

분                 0
평균 누적 와드 제거 횟수    0
dtype: int64

### 4. 챔피언별 와드 설치 데이터 저장

In [53]:
def save_champion_ward_placement_stats_to_pkl():
    conn = connect_db()
    champion_dict = get_champion_dict(conn)
    conn.close()  
    with open("table_data/ward_placement_stats.pkl", "rb") as f:
        ward_placement_stats = pickle.load(f)
    column_mapping = {
        "minute": "분",
        "avg_cumulative_ward_placements": "평균 누적 와드 설치 횟수",
    }
    champion_dataframes = {}
    for champion_id, champion_name in tqdm(champion_dict.items(), desc="Processing Champions"):
        placement_df = ward_placement_stats[ward_placement_stats['champion_id'] == champion_id][['minute', 'avg_cumulative_ward_placements']]
        placement_df = placement_df.rename(columns=column_mapping)
        champion_dataframes[champion_name] = placement_df
    with open("table_data/champion_ward_placement_stats.pkl", "wb") as f:
        pickle.dump(champion_dataframes, f)

In [54]:
save_champion_ward_placement_stats_to_pkl()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_2912\2181235943.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  champion_dict = pd.read_sql_query(champion_dict_query, conn)
Processing Champions: 100%|██████████| 168/168 [00:00<00:00, 988.38it/s]

In [39]:
with open('dashboard_data/champion_main_stats.pkl','rb') as f:
    data = pickle.load(f)
data['닐라'].head(5)

      분  챔피언에게 가한 피해량  받은 피해량  총 획득한 골드량  총 경험치량
8116  0           0.0     0.0      500.0     0.0
8117  1          34.2    35.2      509.9     0.4
8118  2         200.7   291.4      601.6   116.0
8119  3         444.2   726.2      962.4   577.5
8120  4         783.0  1158.6     1360.6   988.3

## 챔피언 승률

In [40]:
def get_champion_win_pick_rate():
    with open('table_data/champion_participant_id.pkl', 'rb') as f:
        champion_participant_id = pickle.load(f)
    with open('table_data/game_end.pkl', 'rb') as f:
        game_end = pickle.load(f)
    with open('table_data/champion_dict.pkl', 'rb') as f:
        champion_dict = pickle.load(f)

    # 데이터 복사
    champion_participant_df = champion_participant_id.copy()
    game_end_df = game_end.copy()
    champion_dict_df = champion_dict[['champion_id', 'champion_name']]

    # 팀 정보 추가
    champion_participant_df['team'] = champion_participant_df['participant_id'].apply(lambda x: 100 if x <= 5 else 200)

    # game_end_df와 병합하여 각 챔피언이 승리했는지 여부 계산
    merged_df = champion_participant_df.merge(game_end_df[['match_id', 'winning_team']], on='match_id')
    merged_df['win'] = merged_df['team'] == merged_df['winning_team']

    # 각 position, champion_id별로 승리 횟수, 총 픽 횟수 집계
    grouped_df = merged_df.groupby(['position', 'champion_id']).agg(
        total_picks=('match_id', 'count'),
        wins=('win', 'sum')
    ).reset_index()

    # 포지션별 경기 수 집계
    position_match_counts = merged_df.groupby('position')['match_id'].nunique().reset_index(name='position_match_counts')
    grouped_df = grouped_df.merge(position_match_counts, on='position')

    # 승률 및 픽률 계산
    grouped_df['win_rate'] = (grouped_df['wins'] / grouped_df['total_picks']).round(4)
    grouped_df['pick_rate'] = (grouped_df['total_picks'] / grouped_df['position_match_counts']).round(4)

    # 챔피언 이름을 추가하기 위해 champion_dict와 병합
    grouped_df = grouped_df.merge(champion_dict_df, on='champion_id')

    # 최종 결과물 구성, 컬럼 이름 수정 및 필요 없는 컬럼 제거
    result_df = grouped_df[['champion_name', 'position', 'win_rate', 'pick_rate', 'total_picks']]
    result_df.columns = ['챔피언', '포지션', '승률', '픽률', '표본 수']

    # 포지션별로 데이터프레임을 분리하여 딕셔너리에 저장
    position_dict = {position: df for position, df in result_df.groupby(result_df['포지션'])}

    # **전체 포지션('ALL') 승률 및 픽률 계산**
    # 전체 픽 수와 승리 수를 챔피언별로 집계
    total_grouped_df = merged_df.groupby('champion_id').agg(
        total_picks=('match_id', 'count'),
        wins=('win', 'sum')
    ).reset_index()

    # 전체 경기 수 계산 (모든 포지션을 포함하여 고유한 경기 수)
    total_matches = merged_df['match_id'].nunique()

    # 전체 승률 및 픽률 계산
    total_grouped_df['win_rate'] = (total_grouped_df['wins'] / total_grouped_df['total_picks']).round(4)
    total_grouped_df['pick_rate'] = (total_grouped_df['total_picks'] / total_matches).round(4)

    # 챔피언 이름을 추가하기 위해 champion_dict와 병합
    total_grouped_df = total_grouped_df.merge(champion_dict_df, on='champion_id')

    # **'ALL' 포지션 데이터프레임 구성**
    all_position_df = total_grouped_df[['champion_name', 'win_rate', 'pick_rate', 'total_picks']]
    all_position_df.columns = ['챔피언', '승률', '픽률', '표본 수']

    # 'ALL' 키로 추가
    position_dict['ALL'] = all_position_df

    # 딕셔너리를 파일로 저장
    with open("dashboard_data/champion_win_pick_rate.pkl", "wb") as f:
        pickle.dump(position_dict, f)

In [41]:
get_champion_win_pick_rate()

In [9]:
with open('dashboard_data/champion_win_pick_rate.pkl', 'rb') as f:
    champion_win_pick_rate = pickle.load(f)

In [10]:
champion_win_pick_rate['ALL'].sort_values('픽률')

       챔피언      승률      픽률   표본 수
85     쉬바나  0.4851  0.0034    202
9       케일  0.4351  0.0044    262
45     트런들  0.4590  0.0051    305
36      소나  0.4756  0.0055    328
167    나피리  0.4668  0.0063    377
..     ...     ...     ...    ...
59     리 신  0.4885  0.2376  14213
41     코르키  0.5197  0.2432  14550
87   그레이브즈  0.5056  0.2716  16247
128    비에고  0.4980  0.2794  16718
122      진  0.4918  0.2884  17252

[168 rows x 4 columns]

## 챔피언 상대 챔피언별 승률

In [77]:
def get_winrate_per_champion():
    conn = connect_db()
    query = "SELECT champion, opponent_champion, winrate, game_count FROM winrate_per_champion"
    df = pd.read_sql(query, conn)
    conn.close()

    # 2. 챔피언별로 상대 챔피언 승률 및 표본 수 딕셔너리 생성
    champion_vs_champion_winrate_dict = {}

    for champion, group in df.groupby('champion'):
        # 컬럼 이름 변경 및 인덱스 새로 설정
        opponent_winrate_df = group[['opponent_champion', 'winrate', 'game_count']].rename(
            columns={'opponent_champion': '상대 챔피언', 'winrate': '승률', 'game_count': '표본 수'}
        )
        opponent_winrate_df = opponent_winrate_df.sort_values(by='승률', ascending=False).reset_index(drop=True)

        # 딕셔너리에 저장
        champion_vs_champion_winrate_dict[champion] = opponent_winrate_df

    # 결과를 pickle 파일로 저장
    output_file_path = "dashboard_data/winrate_per_champion.pkl"
    with open(output_file_path, "wb") as f:
        pickle.dump(champion_vs_champion_winrate_dict, f)

In [78]:
get_winrate_per_champion()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_2912\1845079828.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [79]:
with open('dashboard_data/winrate_per_champion.pkl', 'rb') as f:
    winrate_per_champion = pickle.load(f)

In [80]:
winrate_per_champion['가렌']

      상대 챔피언   승률  표본 수
0        말자하  1.0     2
1        아무무  1.0     8
2        루시안  1.0    16
3        밀리오  1.0     4
4        초가스  1.0    12
..       ...  ...   ...
161       녹턴  0.0     8
162  아우렐리온 솔  0.0     4
163       요릭  0.0     4
164     브라이어  0.0     4
165     말파이트  0.0     8

[166 rows x 3 columns]

In [88]:
with open('dashboard_data/champion_win_pick_rate.pkl', 'rb') as f:
    champion_win_pick_rate = pickle.load(f)
champion_win_pick_rate['BOTTOM']

           챔피언     포지션      승률      픽률  표본 수
0           애니  BOTTOM  0.7500  0.0001     4
1          갈리오  BOTTOM  0.2500  0.0001     4
2    트위스티드 페이트  BOTTOM  0.4615  0.0002    13
3          우르곳  BOTTOM  1.0000  0.0000     1
4        블라디미르  BOTTOM  0.6250  0.0001     8
..         ...     ...     ...     ...   ...
117        오로라  BOTTOM  0.4000  0.0002    10
118         닐라  BOTTOM  0.4990  0.0081   487
119        크산테  BOTTOM  0.5532  0.0008    47
120        스몰더  BOTTOM  0.4802  0.0186  1112
121        흐웨이  BOTTOM  0.4881  0.0140   840

[122 rows x 5 columns]

## 챔피언별 역할군 상대 승률

In [ ]:
def get_champion_winrate_by_role():
    # 데이터 불러오기
    with open('table_data/champion_participant_id.pkl', 'rb') as f:
        champion_participant_id = pickle.load(f)
    with open('table_data/game_end.pkl', 'rb') as f:
        game_end = pickle.load(f)
    with open('table_data/champion_dict.pkl', 'rb') as f:
        champion_dict = pickle.load(f)

    # 중복 제거된 game_end_unique 생성
    game_end_unique = game_end.drop_duplicates(subset=['match_id', 'winning_team'])

    # 역할군 태그 매핑
    tag_mapping = {
        "Assassin": "암살자",
        "Fighter": "전사",
        "Mage": "마법사",
        "Marksman": "원거리 공격",
        "Support": "지원가",
        "Tank": "탱커"
    }

    # 챔피언별 역할군 승률 데이터 딕셔너리
    champion_winrate_dict = {}

    # 각 챔피언에 대해 역할군 승률 계산
    for idx, row in champion_dict.iterrows():
        champion_id = row['champion_id']
        champion_name = row['champion_name']

        # 챔피언의 경기를 필터링
        champion_matches = champion_participant_id[champion_participant_id['champion_id'] == champion_id]['match_id'].unique()
        champion_match_data = champion_participant_id[champion_participant_id['match_id'].isin(champion_matches)][['match_id', 'participant_id', 'champion_id']]
        
        # 챔피언의 역할군 데이터 추가
        champion_match_data = champion_match_data.merge(champion_dict[['champion_id', 'tags']], on='champion_id', how='left')
        
        # 경기 종료 데이터와 결합하여 승리 팀 정보 추가
        champion_match_data = champion_match_data.merge(game_end_unique[['match_id', 'winning_team']], on='match_id', how='left')
        champion_match_data['participant_team'] = champion_match_data['participant_id'].map(lambda x: 100 if x <= 5 else 200)
        
        # 챔피언의 팀 식별
        champion_team_data = champion_match_data[champion_match_data['champion_id'] == champion_id]
        champion_team_data['team'] = champion_team_data['participant_id'].map(lambda x: 100 if x <= 5 else 200)
        
        # 상대 팀 데이터 필터링
        opponent_team_data = champion_match_data[
            champion_match_data\
            .merge(champion_team_data, on='match_id', how='left')[['match_id', 'participant_team_x', 'champion_id_x', 'tags_x', 'winning_team_x', 'team']]
            .apply(lambda row: (row['participant_team_x'] != row['team']), axis=1)
        ]

        # 역할군별 데이터프레임 딕셔너리 생성
        role_winrate_dict = {}

        for target_role_eng, target_role_kor in tag_mapping.items():
            # 상대팀에서 각 챔피언이 특정 역할군(target_role_eng)인지 판단
            opponent_team_data['is_target_role'] = opponent_team_data['tags'].apply(lambda tags: target_role_eng in tags)

            # 각 경기별로 특정 역할군의 수 계산
            role_count_per_match = opponent_team_data.groupby('match_id')['is_target_role'].sum().reset_index()
            role_count_per_match.columns = ['match_id', 'target_role_count']

            # 역할군 명수별 승률 및 표본 수 계산
            win_rates = []
            for count in range(6):  # 0명부터 5명까지의 역할군 명수
                # 특정 역할군 수를 포함한 경기들의 match_id 추출
                role_match_ids = role_count_per_match[role_count_per_match['target_role_count'] == count]['match_id']
                role_match_results = opponent_team_data[opponent_team_data['match_id'].isin(role_match_ids)]

                # 승리 여부 계산
                role_match_results['champion_win'] = role_match_results.apply(
                    lambda row: 1 if row['participant_team'] != row['winning_team'] else 0, axis=1
                )

                # 각 경기별 승/패 결과 중 한 경기당 하나의 값만 남기기 위해 drop_duplicates 사용
                role_match_results = role_match_results.drop_duplicates(subset=['match_id'])

                # 승률 및 표본 수 계산
                sample_size = role_match_results.shape[0]
                if sample_size > 0:
                    win_rate = role_match_results['champion_win'].mean()
                else:
                    win_rate = np.nan

                win_rates.append({'Count': count, '승률': win_rate, '표본 수': sample_size})

            # 역할군별 데이터프레임 생성 후 딕셔너리에 추가
            role_winrate_dict[target_role_kor] = pd.DataFrame(win_rates).set_index('Count')

        # 챔피언 이름을 키로 하고, 역할군 승률 딕셔너리를 값으로 추가
        champion_winrate_dict[champion_name] = role_winrate_dict

    # 딕셔너리를 파일로 저장
    with open("dashboard_data/champion_winrate_by_role.pkl", "wb") as f:
        pickle.dump(champion_winrate_dict, f)

C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  champion_team_data['team'] = champion_team_data['participant_id'].map(lambda x: 100 if x <= 5 else 200)
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  opponent_team_data['is_target_role'] = opponent_team_data['tags'].apply(lambda tags: target_role_eng in tags)
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  opponent_team_data['is_target_role'] = opponent_team_data['tags'].apply(lambda tags: target_role_eng in tags)
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  opponent_team_data['is_target_role'] = opponent_team_data['tags'].apply(lambda tags: target_role_eng in tags)
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  opponent_team_data['is_target_role'] = opponent_team_data['tags'].apply(lambda tags: target_role_eng in tags)
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  opponent_team_data['is_target_role'] = opponent_team_data['tags'].apply(lambda tags: target_role_eng in tags)
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  opponent_team_data['is_target_role'] = opponent_team_data['tags'].apply(lambda tags: target_role_eng in tags)
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  champion_team_data['team'] = champion_team_data['participant_id'].map(lambda x: 100 if x <= 5 else 200)
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  opponent_team_data['is_target_role'] = opponent_team_data['tags'].apply(lambda tags: target_role_eng in tags)
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  opponent_team_data['is_target_role'] = opponent_team_data['tags'].apply(lambda tags: target_role_eng in tags)
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  role_match_results['champion_win'] = role_match_results.apply(
C:\Users\dgjja\AppData\Local\Temp\ipykernel_15916\2665691659.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead


In [79]:
with open('dashboard_data/champion_winrate_by_role.pkl', 'rb') as f:
    champion_winrate_by_role = pickle.load(f)

In [80]:
champion_winrate_by_role['워윅']['암살자']

             승률  표본 수
Count
0      0.520958   334
1      0.504255   940
2      0.521333   750
3      0.530000   200
4      0.518519    27
5      1.000000     1

## 사이드 타워 파괴 횟수

In [147]:
def get_side_building_kill_per_champion():
    with open('table_data/building_kill.pkl', 'rb') as f:
        building_kill = pickle.load(f)
    with open('table_data/champion_participant_id.pkl', 'rb') as f:
        champion_participant_id = pickle.load(f)
    with open('table_data/champion_dict.pkl', 'rb') as f:
        champion_dict = pickle.load(f)

    merged_df = building_kill.merge(champion_participant_id, on=["match_id", "participant_id"], how="left")
    filtered_df = merged_df[merged_df["line_type"].isin(["BOT_LANE", "TOP_LANE"])]
    filtered_df = filtered_df.dropna(subset=["champion_id"])
    per_game_counts = (
        filtered_df.groupby(["match_id", "champion_id"])
        .size()
        .reset_index(name="타워 파괴 횟수")
    )
    building_kill_mean = (
        per_game_counts.groupby("champion_id")["타워 파괴 횟수"]
        .mean()
        .reset_index(name="평균 타워 파괴 횟수")
    )
    building_kill_mean["champion_id"] = building_kill_mean["champion_id"].astype(int)
    champion_dict = champion_dict[["champion_id", "champion_name"]] 
    building_kill_mean = building_kill_mean.merge(champion_dict, on="champion_id", how="left")
    building_kill_mean = building_kill_mean.drop(columns=["champion_id"])
    building_kill_mean = building_kill_mean.rename(columns={"champion_name": "챔피언"})
    building_kill_mean = building_kill_mean[["챔피언", "평균 타워 파괴 횟수"]]
    building_kill_mean = building_kill_mean.sort_values(by="평균 타워 파괴 횟수", ascending=False).reset_index(drop=True)
    
    with open("dashboard_data/champion_sidebuilding.pkl", "wb") as f:
        pickle.dump(building_kill_mean, f)

In [148]:
get_side_building_kill_per_champion()

In [149]:
with open('dashboard_data/champion_sidebuilding.pkl', 'rb') as f:
    building_kill_mean = pickle.load(f)

In [150]:
building_kill_mean

        챔피언  평균 타워 파괴 횟수
0       트런들     2.553922
1       피오라     2.241059
2     트린다미어     2.161754
3        요릭     2.117096
4       나서스     1.939971
..      ...          ...
163     레오나     1.045181
164  블리츠크랭크     1.042857
165    모르가나     1.037037
166      유미     1.018868
167      나미     1.000000

[168 rows x 2 columns]

## 챔피언 20분 이후 솔로킬 횟수

In [102]:
def get_solokill_per_champion():
    with open('table_data/champion_solo_kill_after20.pkl', 'rb') as f:
        champion_kill = pickle.load(f)
    with open('table_data/champion_participant_id.pkl', 'rb') as f:
        champion_participant_id = pickle.load(f)
    with open('table_data/champion_dict.pkl', 'rb') as f:
        champion_dict = pickle.load(f)

    merged_df = champion_kill.merge(champion_participant_id, on=["match_id", "participant_id"], how="left")
    champion_match_kill_count = merged_df.groupby(['champion_id', 'match_id']).size().reset_index(name='solo_kill_count')
    champion_avg_solo_kill = champion_match_kill_count.groupby('champion_id')['solo_kill_count'].mean().reset_index()
    champion_avg_solo_kill.rename(columns={'solo_kill_count': '20분 이후 평균 솔로킬'}, inplace=True)
    champion_avg_solo_kill["champion_id"] = champion_avg_solo_kill["champion_id"].astype(int)    
    champion_dict = champion_dict[["champion_id", "champion_name"]] 
    champion_avg_solo_kill = champion_avg_solo_kill.merge(champion_dict, on="champion_id", how="left")
    champion_avg_solo_kill = champion_avg_solo_kill.drop(columns=["champion_id"])
    champion_avg_solo_kill = champion_avg_solo_kill.rename(columns={"champion_name": "챔피언"})
    champion_avg_solo_kill = champion_avg_solo_kill[["챔피언", "20분 이후 평균 솔로킬"]]
    champion_avg_solo_kill = champion_avg_solo_kill.sort_values(by="20분 이후 평균 솔로킬", ascending=False).reset_index(drop=True)
    
    with open("dashboard_data/champion_solokill_after20.pkl", "wb") as f:
        pickle.dump(champion_avg_solo_kill, f)

In [103]:
get_solokill_per_champion()

In [104]:
with open('dashboard_data/champion_solokill_after20.pkl', 'rb') as f:
    champion_solokill_after20 = pickle.load(f)

In [105]:
champion_solokill_after20

     챔피언  20분 이후 평균 솔로킬
0    나피리       1.854369
1     탈론       1.690967
2      퀸       1.614583
3    카사딘       1.596026
4     제드       1.565804
..   ...            ...
163  소라카       1.000000
164  아무무       1.000000
165   소나       1.000000
166  아이번       1.000000
167  밀리오       1.000000

[168 rows x 2 columns]

In [108]:
def splitpush_champion():
    with open('dashboard_data/champion_sidebuilding.pkl', 'rb') as f:
        building_kill_mean = pickle.load(f)
    with open('dashboard_data/champion_solokill_after20.pkl', 'rb') as f:
        champion_solokill_after20 = pickle.load(f)

    merged_df = pd.merge(building_kill_mean, champion_solokill_after20, on="챔피언", how="outer")
    threshold_tower = merged_df["평균 타워 파괴 횟수"].quantile(0.80)
    threshold_solo_kill = merged_df["20분 이후 평균 솔로킬"].quantile(0.80)

    filtered_data = merged_df[
        (merged_df["평균 타워 파괴 횟수"] >= threshold_tower) &
        (merged_df["20분 이후 평균 솔로킬"] >= threshold_solo_kill)
    ]
    return filtered_data

In [109]:
splitpush_champion()

       챔피언  평균 타워 파괴 횟수  20분 이후 평균 솔로킬
5       그웬     0.044556       1.503344
34      리븐     0.037265       1.428058
88     아칼리     0.046868       1.528432
104     요네     0.135846       1.383550
123    제이스     0.080437       1.372068
156  트린다미어     0.048269       1.490099
163    피오라     0.081433       1.517287

# 스플릿 푸쉬 챔피언 구하기

In [ ]:
# 상위 20퍼